compile: build run

build:
	g++ main.cpp chip8.cpp emulator.cpp\
    -I "C:/ProgramData/mingw64/mingw64/include" \
    -L "C:/ProgramData/mingw64/mingw64/lib" \
    -lSDL3 \
    -o test.exe

run:
	./test.exe